shoulder=mc.joint(name='shoulder_jnt', position=[5,10,-4])
arm=mc.joint(name='forarm_jnt01', position=[3.5,10,-11])
wrist=mc.joint(name='wrist_jnt', position=[3.5,9.5, -19])
handEnd=mc.joint(name='hand_end_jnt', position=[3.5,9.5, -23])
mc.select('wrist_jnt')
mc.duplicate('wrist_jnt', name='fingerOne_jnt')
mc.parent( world=True)
mc.rotate(0,-20,-20)
mc.duplicate(name='fingerTwo_jnt')
mc.rotate(0,20,-28)
mc.parent('fingerTwo_jnt', 'fingerOne_jnt', 'wrist_jnt')
mc.ikHandle(solver= 'ikRPsolver', startJoint='shoulder_jnt', endEffector='wrist_jnt')
